Resources:
  BronzeCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: ${self:custom.bronzeCrawlerName}
      Role:
        Fn::GetAtt:
          - GlueServiceRole
          - Arn
      DatabaseName:
        Ref: SmartHealthcareGlueDatabase
      Description: Crawls raw JSON clinical events in the Bronze zone.
      TablePrefix: bronze_
      Targets:
        S3Targets:
          - Path: s3://${self:custom.bucketName}/${self:custom.bronzePrefix}
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING

  SilverCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: ${self:custom.silverCrawlerName}
      Role:
        Fn::GetAtt:
          - GlueServiceRole
          - Arn
      DatabaseName:
        Ref: SmartHealthcareGlueDatabase
      Description: Crawls cleaned Parquet clinical events in the Silver zone.
      TablePrefix: silver_
      Targets:
        S3Targets:
          - Path: s3://${self:custom.bucketName}/${self:custom.silverPrefix}
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING

  GoldCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: ${self:custom.goldCrawlerName}
      Role:
        Fn::GetAtt:
          - GlueServiceRole
          - Arn
      DatabaseName:
        Ref: SmartHealthcareGlueDatabase
      Description: Crawls curated Gold analytics Parquet metrics.
      TablePrefix: gold_
      Targets:
        S3Targets:
          - Path: s3://${self:custom.bucketName}/${self:custom.goldPrefix}
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING