service: smart-healthcare-data-pipeline
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

custom: ${file(config/custom.yaml)}

functions:
  prepareForecastDataset:
    handler: src.ai.prepare_forecast_dataset.lambda_handler
    runtime: python3.11
    memorySize: 256
    timeout: 420
    role:
      Fn::GetAtt:
        - ForecastDatasetLambdaRole
        - Arn
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
      DATABASE_NAME: ${self:custom.glueDatabaseName}
      WORKGROUP_NAME: ${self:custom.athenaWorkGroupName}
      DESTINATION_KEY: ${self:custom.forecastDatasetKey}

  exportDashboardMetrics:
    handler: src.dashboard.export_dashboard_metrics.lambda_handler
    runtime: python3.11
    memorySize: 256
    timeout: 420
    role:
      Fn::GetAtt:
        - DashboardExportLambdaRole
        - Arn
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
      DATABASE_NAME: ${self:custom.glueDatabaseName}
      GLUE_CATALOG_NAME: ${self:custom.glueCatalogName}
      GOLD_TABLE_NAME: ${self:custom.goldDashboardTableName}
      WORKGROUP_NAME: ${self:custom.athenaWorkGroupName}
      DESTINATION_KEY: ${self:custom.dashboardMetricsKey}

resources:
  - ${file(infra/iam.yaml)}
  - ${file(infra/glue-database.yaml)}
  - ${file(infra/glue-crawlers.yaml)}
  - ${file(infra/glue-jobs.yaml)}
  - ${file(infra/athena.yaml)}
  - ${file(infra/step-functions.yaml)}
  - ${file(infra/sagemaker.yaml)}
  - ${file(infra/outputs.yaml)}
  - ${file(infra/ai-iam.yaml)}
  - ${file(infra/ai-step-functions.yaml)}
  - ${file(infra/dashboard-export-iam.yaml)}