bucketName: smart-healthcare-iot-sim-${aws:accountId}-${sls:stage}

glueDatabaseName: smart_healthcare_${sls:stage}

bronzeCrawlerName: ${self:service}-${sls:stage}-bronze-crawler
silverCrawlerName: ${self:service}-${sls:stage}-silver-crawler
goldCrawlerName: ${self:service}-${sls:stage}-gold-crawler

bronzeToSilverJobName: ${self:service}-${sls:stage}-bronze-to-silver
silverToGoldJobName: ${self:service}-${sls:stage}-silver-to-gold

bronzePrefix: bronze/clinical-deterioration/
silverPrefix: silver/clinical-deterioration/
goldPrefix: gold/clinical-deterioration/department_metrics/

glueScriptKey: scripts/glue/bronze_to_silver.py
goldScriptKey: scripts/glue/silver_to_gold.py

athenaWorkGroupName: ${self:service}-${sls:stage}-workgroup
athenaResultsPrefix: athena-results/

stateMachineName: ${self:service}-${sls:stage}-etl-state-machine

etlScheduleRate: rate(30 minutes)
etlScheduleState: ENABLED

sagemakerNotebookName: ${self:service}-${sls:stage}-forecasting-notebook

forecastDatasetKey: gold/ml/forecasting/input/forecast_training_data.csv
mlInputPrefix: gold/ml/forecasting/input/
mlOutputPrefix: gold/ml/forecasting/output/
forecastScriptKey: scripts/ml/forecast_deterioration_volume.py

aiForecastStateMachineName: ${self:service}-${sls:stage}-ai-forecasting-state-machine
aiScheduleRate: rate(1 hour)
aiScheduleState: DISABLED

sagemakerProcessingInstanceType: ml.t3.medium
sagemakerSklearnImageUri: 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

glueCatalogName: AwsDataCatalog
goldDashboardTableName: gold_department_metrics
dashboardMetricsKey: gold/dashboard/historical/gold_dashboard_metrics.csv
dashboardMetricsPrefix: gold/dashboard/historical/